CREATE TABLE `transacoes_estruturadas` (
  `id_registro` varchar(40) NOT NULL,
  `serial_number` varchar(50) DEFAULT NULL,
  `status_consulta` varchar(20) DEFAULT NULL,
  `tr_id` varchar(40) DEFAULT NULL,
  `tr_status` varchar(20) DEFAULT NULL,
  `tr_tipo` varchar(40) DEFAULT NULL,
  `tr_codigo_retorno` varchar(40) DEFAULT NULL,
  `tr_metodo_captura` varchar(40) DEFAULT NULL,
  `tr_montante` int(11) DEFAULT NULL,
  `cartao_titular` varchar(100) DEFAULT NULL,
  `cartao_bandeira` varchar(40) DEFAULT NULL,
  `cartao_primeiros_digitos` varchar(10) DEFAULT NULL,
  `cartao_ultimos_digitos` varchar(10) DEFAULT NULL,
  `cartao_data_expiracao` varchar(10) DEFAULT NULL,
  `saque_valor` varchar(10) DEFAULT NULL,
  `saque_taxa` int(11) DEFAULT NULL,
  `saque_cupom_id` varchar(20) DEFAULT NULL,
  `split_wallet_id1` varchar(40) DEFAULT NULL,
  `split_wallet_id2` varchar(40) DEFAULT NULL,
  `split_wallet_id1_chargeable` varchar(40) DEFAULT NULL,
  `split_wallet_id2_chargeable` varchar(40) DEFAULT NULL,
  `split_wallet_id1_montante` varchar(40) DEFAULT NULL,
  `split_wallet_id2_montante` varchar(40) DEFAULT NULL,
  `split_regra_texto_json` text,
  `tr_data_inicio` varchar(50) DEFAULT NULL,
  `tr_data_fim` varchar(50) DEFAULT NULL,
  `tr_data_inicio_autorizacao` varchar(50) DEFAULT NULL,
  `tr_data_fim_autorizacao` varchar(50) DEFAULT NULL,
  `origem_registro` varchar(80) DEFAULT NULL,
  `merchant_number` varchar(200) DEFAULT '',
  `merchant_wallet` varchar(200) DEFAULT '',
  `merchant_name` varchar(200) DEFAULT '',
  `percentagem_mdr` decimal(12,6) DEFAULT NULL,
  `percentagem_mdr_bandeira` decimal(10,5) DEFAULT '0.00000',
  PRIMARY KEY (`id_registro`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

